import type { Stage } from "./types";

/** Hạng mục báo giá / discovery — mô tả canvas demo (FE hardcode). */
export type QuoteScopeItem = {
  id: string;
  code: string;
  title: string;
  stage: Stage;
  group: "A" | "setup" | "B1" | "B2";
  asIs: string;
  toBe: string;
  rules: string[];
};

export const QUOTE_SCOPE: QuoteScopeItem[] = [
  {
    id: "a1",
    code: "A1",
    title: "Nền tảng & phân quyền",
    stage: "access",
    group: "A",
    asIs: "Chủ / QL / lễ tân / GV thao tác rải trên Zalo; không ACL trên file.",
    toBe: "3 chi nhánh · 7 phòng; khóa gắn CN, phòng linh hoạt; 4 vai trò trên CRM.",
    rules: ["GV không xem học phí & SĐT HV", "Khóa cố định chi nhánh", "Phòng đổi trong CN"],
  },
  {
    id: "a2",
    code: "A2",
    title: "Khóa học & buổi",
    stage: "courses",
    group: "A",
    asIs: "Lịch tuần trên Google Calendar + tin Zalo; buổi hủy báo tay.",
    toBe: "Khóa (thể loại, level, khung, GV, KG–KT, CN) → sinh buổi; hủy / đổi giờ–phòng–GV.",
    rules: ["~8 buổi/tháng", "1 GV / buổi", "Không trùng phòng–giờ", "Hủy buổi → HV không mất buổi"],
  },
  {
    id: "a2-class",
    code: "A2",
    title: "Buổi học",
    stage: "classes",
    group: "A",
    asIs: "Đổi giờ / phòng / GV nhắn nhóm Zalo.",
    toBe: "Sửa buổi trên CRM; chặn trùng phòng–giờ; hủy không trừ buổi gói.",
    rules: ["Trạng thái upcoming / ongoing / completed / cancelled", "Không học bù"],
  },
  {
    id: "a3",
    code: "A3",
    title: "Tuyển sinh / ghi danh",
    stage: "leads",
    group: "A",
    asIs: "Nhận giữa khóa theo cảm tính level; lớp đầy thì QL gợi khung khác trên Zalo.",
    toBe: "Cửa sổ ghi danh + rule level + sĩ số 10–15; đầy → gợi ý khóa khác.",
    rules: ["Begin: dừng nhận từ buổi 4–5", "Inter: nhận buổi lẻ", "Advance: buổi 1 & 5", "Đổi lớp cuối tháng"],
  },
  {
    id: "a4",
    code: "A4",
    title: "Học viên & phụ huynh",
    stage: "students",
    group: "A",
    asIs: "Hồ sơ rải Excel; trẻ em liên hệ PH trên Zalo.",
    toBe: "Hồ sơ HV + ngày sinh, email; trẻ em: điểm danh theo tên HV, liên hệ & TT theo PH.",
    rules: ["Nhiều khóa song song", "Nghỉ / hủy ghi danh → giữ hồ sơ"],
  },
  {
    id: "a5",
    code: "A5",
    title: "Giáo viên",
    stage: "teachers",
    group: "A",
    asIs: "GV nghỉ tự tìm người dạy thay, báo QL.",
    toBe: "Hồ sơ GV (style, lớp, CN); buổi nghỉ → gán giáo viên dự phòng trên CRM.",
    rules: ["1 GV / buổi", "Backup không đổi lịch khóa"],
  },
  {
    id: "a6",
    code: "A6",
    title: "Gói buổi & trừ buổi",
    stage: "packages",
    group: "A",
    asIs: "Trừ buổi tay sau điểm danh; không học bù.",
    toBe: "Gói 1 / 3 / 6 / 12 tháng; điểm danh có mặt → trừ 1 buổi.",
    rules: ["Không học bù", "Nghỉ không bảo lưu → mất buổi, không hoàn"],
  },
  {
    id: "a7",
    code: "A7",
    title: "Thu học phí & công nợ",
    stage: "payment",
    group: "A",
    asIs: "Thu quầy tiền mặt / CK, gửi ảnh bill Zalo; nợ vẫn cho học.",
    toBe: "Phiếu thu 1 lần hoặc từng đợt; TM / CK + ảnh bill; nợ vẫn vào lớp.",
    rules: ["Cọc chỉ gói 6 & 12 tháng", "Báo cáo đã thu / nợ theo CN"],
  },
  {
    id: "a8",
    code: "A8",
    title: "Bảo lưu",
    stage: "holds",
    group: "A",
    asIs: "HV xin Zalo → QL duyệt miệng.",
    toBe: "Phiếu BL trên CRM; QL duyệt; giữ chỗ sĩ số; hạn gói + buổi còn.",
    rules: ["≥ 3 tháng tặng BL", "Gói ngắn mua BL lẻ", "Lễ / hủy lớp không tính hạn BL"],
  },
  {
    id: "a9",
    code: "A9",
    title: "Điểm danh tay",
    stage: "attendance",
    group: "A",
    asIs: "Gọi tên / tick giấy.",
    toBe: "Lễ tân / QL đánh có mặt / vắng trên CRM → trừ buổi nếu có mặt.",
    rules: ["HV không tự điểm", "Vắng không trừ (không học bù)"],
  },
  {
    id: "a10",
    code: "A10",
    title: "Điểm danh QR",
    stage: "qr",
    group: "A",
    asIs: "Chưa làm (discovery còn mở cụm QR).",
    toBe: "Mã QR theo buổi — demo quét hộ, chưa camera thật.",
    rules: ["Cùng trừ buổi như điểm danh tay", "TODO: ai quét / cửa sổ giờ"],
  },
  {
    id: "a11",
    code: "A11",
    title: "Lịch / Google Calendar",
    stage: "schedule",
    group: "A",
    asIs: "1 lịch Google chung của trung tâm; nội bộ xem.",
    toBe: "Sync buổi CRM → Calendar trung tâm (mock, chưa OAuth).",
    rules: ["Chỉ nội bộ (chủ / GV / NV)", "HV / PH không nhận GCal cá nhân"],
  },
  {
    id: "a12",
    code: "A12",
    title: "Promotion / voucher",
    stage: "promotions",
    group: "A",
    asIs: "KM loan tin Zalo / Facebook.",
    toBe: "Catalog mã giảm / voucher trên CRM.",
    rules: ["Bật / tắt mã", "Hạn dùng"],
  },
  {
    id: "a13",
    code: "A13",
    title: "Chăm sóc & thông báo",
    stage: "campaigns",
    group: "A",
    asIs: "Chúc SN / nhắc phí nhắn tay.",
    toBe: "Sinh nhật HV; Zalo / email hàng loạt cho HV hoặc PH (demo local).",
    rules: ["Chưa nối Zalo OA / SMTP"],
  },
  {
    id: "a14",
    code: "A14",
    title: "Theo dõi doanh thu",
    stage: "reports",
    group: "A",
    asIs: "Chủ hỏi QL đã thu / nợ theo chi nhánh.",
    toBe: "Báo cáo đã thu · còn nợ · theo gói · theo CN.",
    rules: ["GV không xem số tiền", "Seed tháng 08/2026"],
  },
  {
    id: "rooms",
    code: "A1",
    title: "Phòng tập",
    stage: "classrooms",
    group: "A",
    asIs: "7 phòng; khóa không cố định phòng — đông thì phòng lớn.",
    toBe: "Gán phòng theo buổi; lọc theo chi nhánh.",
    rules: ["Q10: MI1 MI2 MON3 MON4", "Q3: Room A", "PN: MI3 MI4"],
  },
  {
    id: "b1-web",
    code: "B1",
    title: "Website công khai",
    stage: "website",
    group: "B1",
    asIs: "Không thuộc vận hành lớp hiện tại.",
    toBe: "Site giới thiệu, admin nội dung, form/Zalo, SEO nền — preview, không login HV/GV.",
    rules: ["Không thu tiền trên site này", "Preview hardcode"],
  },
  {
    id: "b1-portal",
    code: "B1",
    title: "Portal học viên & giáo viên",
    stage: "portal",
    group: "B1",
    asIs: "HV/PH xin BL / đổi lớp qua Zalo — không tự thao tác CRM.",
    toBe: "Đăng nhập xem lịch, lớp, sĩ số, khóa, hồ sơ, KM, video — chỉ xem.",
    rules: ["Không thu tiền trên portal", "Preview hardcode"],
  },
  {
    id: "b1-store",
    code: "B1",
    title: "Website bán hàng cơ bản",
    stage: "store",
    group: "B1",
    asIs: "Ngoài as-is lớp–gói.",
    toBe: "Catalog / giỏ / thanh toán cơ bản — preview.",
    rules: ["Không thay thu học phí A7"],
  },
  {
    id: "b1-care",
    code: "B1",
    title: "AI Tuyển sinh & trực page 24/7",
    stage: "care-ai",
    group: "B1",
    asIs: "Lễ tân trực chat ngoài giờ hoặc bỏ lỡ tin.",
    toBe: "Dolphin Care đa kênh (web · Fanpage · Zalo OA) — preview hội thoại.",
    rules: ["Tư vấn lớp / lấy SĐT / hẹn học thử", "Chưa nối OA thật"],
  },
  {
    id: "b2-tasks",
    code: "B2",
    title: "Quản lý tác vụ",
    stage: "tasks",
    group: "B2",
    asIs: "Chia việc trên Zalo.",
    toBe: "Giao việc, hạn, trạng thái, lọc — không Jira sprint/epic.",
    rules: ["Nội bộ studio"],
  },
  {
    id: "b2-pay",
    code: "B2",
    title: "Thanh toán online",
    stage: "payment",
    group: "B2",
    asIs: "Thu quầy (A7).",
    toBe: "Cổng online trên CRM (phiếu method = Online CRM).",
    rules: ["Khác thu tay A7", "Demo local, chưa cổng thật"],
  },
  {
    id: "b2-rent",
    code: "B2",
    title: "Đặt phòng thuê",
    stage: "rentals",
    group: "B2",
    asIs: "Thuê studio ngoài giờ — khác gán phòng lớp.",
    toBe: "Phiếu thuê + xác nhận cọc trên CRM.",
    rules: ["Không trừ buổi HV", "Không phải spa 1:1"],
  },
  {
    id: "b2-aiops",
    code: "B2",
    title: "AI trợ lý vận hành",
    stage: "ai-ops",
    group: "B2",
    asIs: "Lễ tân nhập form tay.",
    toBe: "Câu lệnh giọng/văn bản → mở form; cảnh báo hết buổi / nợ.",
    rules: ["Demo local", "Không NLU thật"],
  },
  {
    id: "b2-intel",
    code: "B2",
    title: "Dolphin Intelligent",
    stage: "intelligent",
    group: "B2",
    asIs: "Sửa data tay khi phát hiện sai.",
    toBe: "Cảnh báo cuối ngày + đề xuất; admin chọn → hệ thống áp dụng (demo).",
    rules: ["Giám sát EOD", "Chưa backend"],
  },
];

const BY_STAGE: Partial<Record<Stage, QuoteScopeItem>> = Object.fromEntries(
  QUOTE_SCOPE.filter((item, i, all) => all.findIndex((row) => row.stage === item.stage) === i).map((item) => [
    item.stage,
    item,
  ]),
);

export function quoteScopeForStage(stage: Stage): QuoteScopeItem | undefined {
  return BY_STAGE[stage];
}

export const QUOTE_HUB_CORE = QUOTE_SCOPE.filter((item) => ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14"].includes(item.id));

export const QUOTE_HUB_ADDON = QUOTE_SCOPE.filter((item) => item.group === "B1" || item.id === "b2-tasks" || item.id === "b2-rent" || item.id === "b2-aiops" || item.id === "b2-intel");
